[package]
edition = "2021"
name = "test_helpers"
version = "0.0.0"

[dependencies]
chrono = { version = "0.4" }
fuels = { version = "0.33", features = ["fuel-core-lib"] }
tokio = { version = "1.15", features = ["rt", "macros"] }
