[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "pool_contract"

[dependencies]
pool_abi = { path = "../pool_abi" }
microchain_helpers = { path = "../microchain_helpers" }
vault_abi = { path = "../vault_abi" }
